### ISSUE TITLE
Docs for ‘wxme/scheme’: ‘racket-editor%’ should be ‘scheme-editor%’.

### ISSUE THREAD

**Issue by gfbee** [racket/wxme#1]
The docs for `wxme/scheme` mention that the editor for racket boxes is `racket-editor%`, but that doesn't seem to exist. A quick look through the repo suggests that racket boxes still use `scheme-editor%`.

**Comment by stamourv** [comment]
FIx pushed: https://github.com/racket/gui/commit/f2a202eb30fe8bc6a18931f86fa2e75c33ca8071

Thanks for the report!
